# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_personaje_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='icono',
            field=models.CharField(max_length=500),
        ),
    ]
