# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170925_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='icono',
            new_name='sprite',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='vida',
        ),
    ]
