# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20171023_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='sprite',
            new_name='icono',
        ),
    ]
